name: PLEXALYZER Analysis
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PLEXALYZER Analysis
        uses: plexicus/plexalyzer-action@main
        with:
          plexalyzer-token: ${{ vars.PLEXALYZER_TOKEN }}
          repo-id: ${{ vars.COVULOR_REPO_ID }}
          repo-name: ${{ github.repository }}
          branch: ${{ github.event.pull_request.base.ref }}
          url: ${{ github.event.repository.clone_url }}
