name: PLEXALYZER Analysis
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PLEXALYZER Analysis
        uses: plexicus/plexalyzer-action@v1
        with:
          plexalyzer-token: ${{ vars.PLEXALYZER_TOKEN }}
          repo-id: ${{ vars.COVULOR_REPO_ID }}
